version: "3.8"
services:
  mod-host:
    image: mod-host:latest
    container_name: mod-host
    stdin_open: true # docker run -i
    tty: true # docker run
    environment:
      - USER_NAME=${USER_NAME}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /dev/shm:/dev/shm:rw
      - /home/${USER_NAME}/mod-user-files:/mod/user-files
      - /home/${USER_NAME}/mod-data:/mod/data
      - /home/${USER_NAME}/mod-pedalboards:/mod/.pedalboards
    build:
      context: ./mod-host
    ulimits:
      memlock: 819200000
      rtprio: 99
    expose:
      - "5555"
      - "5556"
    ports:
      - 5555:5555
      - 5556:5556

  mod-ui:
    image: mod-ui:latest
    container_name: mod-ui
    environment:
      - USER_NAME=${USER_NAME}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /dev/shm:/dev/shm:rw
      - /home/${USER_NAME}/mod-user-files:/mod/user-files
      - /home/${USER_NAME}/mod-data:/mod/data
      - /home/${USER_NAME}/mod-pedalboards:/mod/.pedalboards
    build:
      context: ./mod-ui
    ulimits:
      memlock: 819200000
      rtprio: 99
    ports:
      - 8081:8081
      - 8888:8888

  mod-ui-docker:
    image: raidolo/mod-ui:latest
    container_name: mod-ui
    environment:
      - USER_NAME=${USER_NAME}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /dev/shm:/dev/shm:rw
      - /home/${USER_NAME}/mod-user-files:/mod/user-files
      - /home/${USER_NAME}/mod-data:/mod/data
      - /home/${USER_NAME}/mod-pedalboards:/mod/.pedalboards
    build:
      context: ./mod-ui
    ulimits:
      memlock: 819200000
      rtprio: 99
    ports:
      - 8081:8081
      - 8888:8888
